= Moss Design Overview

Moss is a library for GNU make that streamlines the creation of rules and dependencies for software build artifacts. The core concepts within this library are:

1. Seeds - modular units of software configuration used to define one or more artifacts
2. Artifacts - software build products that may be created for multiple architectures and variants
3. Architectures - used to specialize seeds and tools for artifact creation
4. Variants - global options for tools
5. Tools - used to compile source code and create artifacts

These core concepts are defined and extended entirely through makefile variable definitions.
Knowledge of toolchain and architecture specifics are decoupled from the description of the software itself.
Moss manages the creation and application of all makefile rules required for multiple languages, artifacts, architectures, toolchains, and variants.
This separation of concerns avoids many pitfalls of traditional make-based build systems.

== Seeds

Seeds define a series of base variables and configuration options that may be used by artifact definitions as a source of configuration.

A given seed may be used to produce multiple artifacts for multiple architectures without requiring duplication of the seed definition.
The architecture-specific 'specializations' are created from the base seed 'template'.
Architecture-specific options and overrides can be specified through variables that 'overload' the base definition for the seed.

A formalized syntax is used to specify and use conditional boolean switches and named string options to specialize the artifacts produced by a seed.
Configuration is the ideal way to provide the setting that are used during specialization to fine tune the artifacts that are formed.
Think menuconfig or kconfig.

== Artifacts

Artifacts are used to define the build outputs created by Moss.
Seeds are used by artifacts as a mechanism for configuration.

Most artifacts will require creation of object files using a compiler.
Source code may also be transcoded before this compilation step.
Translation is converts code from one language from another language.
Compilation is converts source code into object code.
Some artifacts may be produced directly from source files.
Moss manages the chaining of translation and compilation to ultimately produce and object file from source file as required.

Each artifact is produced in isolation.
This guarantees that object and artifact files will never be clobbered, even if multiple artifacts use the source code in different ways.
Artifacts are produced in a way that encourages creation of small libraries that are combined to produce complex artifacts.

== Architectures

An architecture definition specifies a toolchain. For example armv5-gcc would specify a gcc cross compiler. And armv5-clang would specify a clang cross compile. In order to build the same seed for the same processor with two different tools, two different architectures must be created.

Architecture is the mechanism for customized compilation of seeds for a particular target. Different seeds compiled for the same architecture may have different toolchain settings. The architecture is the means of selection. Seeds compiled for the same architecture may be linked together. A mixing of architectures is not supported.

A build architecture is defined by a specific CPU type and associated instruction set.

Examples: host, amd64, cortex-m4, cortex-r7, avr, mipsel, etc.

Good discussion on architecture naming here: http://clang.llvm.org/docs/CrossCompilation.html

== Variants

A build variant is a selection that applies across all architectures and toolchains (in most cases). An example would be debug vs production.

Variants provide the mechanism for compiling multiple seeds for the same architecture with different collections of settings that apply to all seeds. Example use cases that apply here are debug, production, or special test build variants.

== Tools

Tool are used to create all build artifacts.

A tool does not possess any knowledge of Moss build architecture or variant.
Tools are specialized through architecture and variant by setting appropriate tool options to create appropriate artifacts.

1. Transcode: The output is generated source code, not object code.

2. Compile: The output is object code.

3. Form: The output is a build artifact that may contain object code or files.
