YEAST.BUILD.TREE ?= yeast.build

ifdef YEAST_TOOL
YEAST.ARCH_TOOL.NAME = $(addprefix $(addsuffix .,$(YEAST_ARCH)),$(YEAST_TOOL))
else
YEAST.ARCH_TOOL.NAME = $(YEAST_ARCH)
endif

ifneq ($(strip $(YEAST.BUILD.TREE)),)
YEAST.OBJECT.PATH = $(YEAST.BUILD.TREE)/obj/$(YEAST.ARCH_TOOL.NAME)/
YEAST.EXECUTABLE.PATH = $(YEAST.BUILD.TREE)/bin/$(YEAST.ARCH_TOOL.NAME)/
YEAST.STATIC_LIB.PATH = $(YEAST.BUILD.TREE)/lib/$(YEAST.ARCH_TOOL.NAME)/
YEAST.SPORE.SUFFIX = $(addprefix .,$(YEAST.ARCH_TOOL.NAME)).spore
YEAST.SPORE.PATH = $(YEAST.BUILD.TREE)/
else
YEAST.SPORE.SUFFIX = .spore
endif


YEAST.SPORES += lite
lite.source = test.c

YEAST.SPORES += heavy
heavy.source = test.c

include yeast.mk
