TOOL.STATIC_LIB.CMD = ar -r $2 $1
TOOL.STATIC_LIB.SUFFIX = .ar
TOOL.STATIC_LIB.PREFIX = lib

TOOL.C.COMPILE = gcc -c $(TOOL.C.FLAGS) -o $2 $1
TOOL.C.DEPEND = gcc $(TOOL.C.FLAGS) -MM -MT $3 -MF $2 $1

TOOL.OBJECT.SUFFIX = .o
TOOL.DEPEND.SUFFIX = .d
