TOOL.STATIC_LIB.CMD = ar -r $2 $1
TOOL.STATIC_LIB.SUFFIX = .ar
TOOL.STATIC_LIB.PREFIX = lib

TOOL.EXECUTABLE.CMD = gcc -o $2 $1

TOOL.C.COMPILE = gcc -c $(TOOL.C.FLAGS) -o $2 -MD $1

TOOL.OBJECT.SUFFIX = .o
TOOL.DEPEND.SUFFIX = .d
